// Alain Pilon 
// date: 4 juillet 2023
// Fichier de tests des différentes fonctions de mon API REST

// test de API pour récupérer tous les livres
###
GET http://127.0.0.1:8000/api/livres

// test de API pour récupérer tous les livres dont l'isbn est demandé
###
GET http://127.0.0.1:8000/api/livres/isbn/9782896152254

// test de API pour récupérer tous les livres qui contiennent un titre
###
GET http://127.0.0.1:8000/api/livres/titre/café

// test de API pour récupérer tous les livres qui contiennent un titre
###
GET http://127.0.0.1:8000/api/livres/titre/flots

// test de API pour récupérer tous les livres qui contiennent un certain auteur
###
GET http://127.0.0.1:8000/api/livres/auteur/t

// test de API pour récupérer tous les livres qui contiennent un certain résumé
###
GET http://127.0.0.1:8000/api/livres/resume/noc

// test de API pour récupérer tous les livres qui contiennent un certain auteur
###
GET http://127.0.0.1:8000/api/livres/auteur/o

// test. de API POST pour ajouter un livre dans la BD
###
POST http://127.0.0.1:8000/api/livres
Content-type: application/json

{
    "_id": "9782896151177",
    "titre": "Mon beau titre",
    "auteur": "Moi",
    "editeur": "Lui",
    "nbPages": 33,
    "langue": "français/french",
    "prix": 99.95,
    "resume": "Bonjour. voici un résumé",
    "date": "2023-07-31"
}

// test. de API PUT pour modifier un livre dans la BD
###
PUT http://127.0.0.1:8000/api/livres/9782896151177
Content-type: application/json

{
    "titre": "Mon NOUVEAU beau titre",
    "auteur": "Moi en version 2",
    "editeur": "Lui encore LUI",
    "nbPages": 99,
    "langue": "anglais/english",
    "prix": 999.95,
    "resume": "Bonjour. voici ENCORE un résumé",
    "date": "2023-07-28"
}

// test. de API DELETE pour supprimer un livre de la BD
###
DELETE http://127.0.0.1:8000/api/livres/9782896151177

// test de API pour récupérer tous les users
###
GET http://127.0.0.1:8000/api/users

// test de API pour récupérer tous les usagers dont l'id est demandé
###
GET http://127.0.0.1:8000/api/users/_id/64a47added3c0c34dae0ba3c

// test de API pour récupérer tous les usagers qui contiennent un nom donné
###
GET http://127.0.0.1:8000/api/users/nom/o

// test de API pour récupérer tous les usagers qui contiennent un login donné
###
GET http://127.0.0.1:8000/api/users/login/ai

// test. de API POST pour ajouter un usager dans la BD
###
POST http://127.0.0.1:8000/api/users
Content-type: application/json

{
    "nom": "Nouveau 4",
    "login": "nouveau4@gmail.com",
    "pwd": "1234",
    "date": "2023-06-29"
}

// test. de API PUT pour modifier un usager dans la BD
###
PUT http://127.0.0.1:8000/api/users/64a47b31ed3c0c34dae0ba41
Content-type: application/json

{
    "nom": "Nouveau ABC",
    "login": "nouveauABC@gmail.com",
    "pwd": "1234",
    "date": "2023-06-29"
}

// test. de API DELETE pour supprimer un usager de la BD
###
DELETE http://127.0.0.1:8000/api/users/64a47b31ed3c0c34dae0ba41
