// Alain Pilon 
// date: 4 juillet 2023
// Fichier de tests des différentes fonctions de mon API REST

// test de API pour récupérer tous les messages
###
GET http://127.0.0.1:8000/api/messages

// test de API pour récupérer tous les messages dont l'isbn est demandé
###
GET http://127.0.0.1:8000/api/messages/123

// test de API pour récupérer tous les messages dont l'isbn est demandé
###
GET http://127.0.0.1:8000/api/messages/12344

// test de API pour récupérer tous les messages qui contiennent un titre
###
GET http://127.0.0.1:8000/api/messages/description/bla

// test de API pour récupérer tous les messages qui contiennent un titre
###
GET http://127.0.0.1:8000/api/messages/titre/222

// test de API pour récupérer tous les messages qui contiennent un certain auteur
###
GET http://127.0.0.1:8000/api/messages/auteur/jo

// test. de API POST pour ajouter un messages dans la BD
###
POST http://127.0.0.1:8000/api/messages
Content-type: application/json

{ "_id": "12344",
    "titre": "3333 Comment faire fructifier votre argent sans risques",
    "auteur": "33333@trucmachin.com",
    "description": "33333 Dans ce sujet nous allons blabla",
    "date": "2022-10-25T05:00:00.000Z",
    "langue": "français",
    "commentaires": [
       {  "commentaire": "Tu dis n'importe quoi",
          "auteur": "jtecroispas@ici.com",
          "date": "2022-10-25T04:00:00.000Z"
       },
       {  "commentaire": "autre chose",
          "auteur": "jtecroispas@ici.com",
          "date": "2022-10-25T06:00:00.000Z"
       }]
  }


// test. de API PUT pour modifier un messages dans la BD
###
PUT http://127.0.0.1:8000/api/messages/12344
Content-type: application/json

{ 
    "titre": "4444 Comment faire fructifier votre argent sans risques",
    "auteur": "4444@trucmachin.com",
    "description": "4444 Dans ce sujet nous allons blabla",
    "date": "2022-10-25T05:00:00.000Z",
    "langue": "français",
    "commentaires": [
       {  "commentaire": "Tu dis n'importe quoi",
          "auteur": "jtecroispas@ici.com",
          "date": "2022-10-25T04:00:00.000Z"
       },
       {  "commentaire": "autre chose",
          "auteur": "jtecroispas@ici.com",
          "date": "2022-10-25T06:00:00.000Z"
       }]
  }

// test. de API DELETE pour supprimer un message de la BD
###
DELETE http://127.0.0.1:8000/api/messages/12344
